# Generated by Django 3.2 on 2021-05-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
